apiVersion: v1
kind: ServiceAccount
metadata:
  name: fake-operator
  namespace: operator-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fake-operator-role
  namespace: operator-demo
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: ["demo.com"]
  resources: ["myapps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fake-operator-binding
  namespace: operator-demo
subjects:
- kind: ServiceAccount
  name: fake-operator
  namespace: operator-demo
roleRef:
  kind: Role
  name: fake-operator-role
  apiGroup: rbac.authorization.k8s.io
