apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-not-ready-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/krishnendusukumar/k8s
    targetRevision: HEAD
    path: node_not_ready
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exit-code-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/krishnendusukumar/k8s
    targetRevision: HEAD
    path: exit-code-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: liveness-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/krishnendusukumar/k8s
    targetRevision: HEAD
    path: liveness-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hardcoded-url-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/krishnendusukumar/k8s
    targetRevision: HEAD
    path: hardcoded-url
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
