apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-k8s-apps
  namespace: argocd
spec:
  # The generator tells it what to look for
  generators:
  - git:
      repoURL: https://github.com/krishnendusukumar/k8s
      revision: HEAD
      # Look for any folder that contains YAMLs/deployments
      directories:
      - path: 'kyverno-demo'
  # The template is how it creates each application
  template:
    metadata:
      # Automatically name the Argo app after the folder name
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/krishnendusukumar/k8s
        targetRevision: HEAD
        # Automatically use the folder path
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true