apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-pending-demo
  namespace: default
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: cpu-pending
  template:
    metadata:
      labels:
        app: cpu-pending
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: "100" 
