apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-concurrency-forbid
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: long-job
            image: busybox
            command: ["/bin/sh", "-c", "sleep 90"]
          restartPolicy: OnFailure
