apiVersion: v1
kind: Namespace
metadata:
  name: kubegrade
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubegrade-scanner
  namespace: kubegrade
data:
  CLUSTER_NAME: "my-eks"
  CLUSTER_TOKEN: "kg_1zTeJtA9A4IHDc6p5ZEo4Vtz62yTUDXIxDCs8qjg"
  MATRIX_HOST: "api.app.kubegrade.com"
  MATRIX_PORT: "443"
  MATRIX_REQUIRE_SSL: "true"
  KUBEGRADE_CONFIG_PATH: "/kubegrade/config.yaml"
  SQLITE_PATH: "/kubegrade"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubegrade-scanner
  namespace: kubegrade
  labels:
    app: kubegrade-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubegrade-scanner
  template:
    metadata:
      labels:
        app: kubegrade-scanner
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: kubegrade-scanner
        image: public.ecr.aws/kubegrade/scanner:v0.14.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: kubegrade-scanner
        volumeMounts:
        - name: kubegrade-storage
          mountPath: /kubegrade
      volumes:
      - name: kubegrade-storage
        emptyDir: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-wide-read
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubegrade-scanner
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kubegrade
roleRef:
  kind: ClusterRole
  name: cluster-wide-read
  apiGroup: rbac.authorization.k8s.io
