apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: no_storage_created
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
