apiVersion: apps/v1
kind: Deployment
metadata:
  name: exit127-broken
  labels:
    app: exit127-broken
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: exit127-broken
  template:
    metadata:
      labels:
        app: exit127-broken
    spec:
      containers:
      - name: command-not-found
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Starting application..."
          fakecommand123
          echo "Finished!"
