apiVersion: apps/v1
kind: Deployment
metadata:
  name: exit126-broken
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exit126-broken
  template:
    metadata:
      labels:
        app: exit126-broken
    spec:
      containers:
      - name: bad-permissions
        image: alpine:latest
        command: ["/bin/sh","-c"]
        args:
        - |
          echo '#!/bin/sh' > /app.sh
          echo 'echo this is a script' >> /app.sh
          chmod +x /app.sh
          /app.sh