apiVersion: apps/v1
kind: Deployment
metadata:
  name: exit1-broken
  labels:
    app: exit1-broken
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: exit1-broken
  template:
    metadata:
      labels:
        app: exit1-broken
    spec:
      containers:
      - name: app
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          wget -q --timeout=3 -O- "$BACKEND_URL" || exit 1
        env:
        - name: BACKEND_URL
          value: "http://backend:5678"
